### ISSUE TITLE
why do you writing cutscene logic in C#?

### ISSUE THREAD

**Issue by sFisherE** [cmark89/Eglantine#1]
I am referencing your game structure,it's great,but i noticed there is scheduler.lua which can do the cutscene logic,but you didn't use it. i want to know why?

**Comment by cmark89** [comment]
Hello,

Thank you for the email.  In an earlier version of the game, all the
cutscene / game event logic actually did use Lua and the scheduler you see
in the repository (if you check back some number of commits, I'm sure
you'll see the old files).  However, since I develop on Linux, I ran into a
lot of problems when I tried to port the game to Windows.  The biggest
issue I had was that none of the C# / Lua bindings available for Windows
worked.  Some were outdated, some were incomplete, and some simply crashed
when the scheduler started for some reason.  Since Lua is not my language
of choice, I really had no idea where to even start troubleshooting the
problems with the scheduler, so I just looked for some set of bindings that
would replicate the success I had with MonoLuaInterface on Linux.

After probably two weeks of unsuccessful troubleshooting, I got so
frustrated that I just wrote another scheduler in C# and ported over all
the cutscene and event scripts.  It's hacky, it's unoptimal, but at least
it worked.  I'm sure someone with more patience than I could make it work
using Lua, but I was so frustrated that I just gave up.

Hope that was helpful!  If you have any other questions, let me know.

**Comment by sFisherE** [comment]
thank you very much.
your Implementation of scheduler in C# is great.The unity3d engine use Coroutine to achieve the same function(and this is a hack version:http://wiki.unity3d.com/index.php/CoroutineScheduler).
I am freshman to lua and am serching an elegant way to do cutscene logic in lua, your answer is important to me.
Otherwise Unity3d has some plugins to do cutscene in editor,but it is not flexible to me(there is to much custom action in my game).so using script to control cutscene logic is my best choice.so i am still trying.

**Comment by cmark89** [comment]
If you're using Unity, it may have some specific plugins for Lua without
the problems that come with LuaInterface.  If so, the scheduler might be a
useful option.  Unfortunately, not being familiar with Unity, I can't say I
know much about your options.  If you're interested, I might upload the
current version of my C# scheduler later; I've added a lot of additional
functionality to it since I stopped working on Eglantine, such as the
ability to add tags to scripts, arbitrarily pause and resume by tags, and
so forth.

Either way, good luck on your project!

**Comment by sFisherE** [comment]
It is so kind of you.I appreciate your solution very very much.

**Comment by cmark89** [comment]
Update scheduler can be found here: https://github.com/cmark89/ObjectivelyRadicalScheduler/

**Comment by sFisherE** [comment]
wonderful!!!
Many thanks!
